-- ============================================================================
-- Seed: full 21-day content (Kenneth E. Hagin — "Growing Up, Spiritually")
-- ============================================================================

insert into public.daily_content
  (day_number, week_number, chapter, topic, key_truth, practical_exercise, prayer_focus, is_review_day, weekly_challenge, resources)
values
-- WEEK 1: LOCATING YOURSELF SPIRITUALLY
  (1, 1, 'Chapter 1', 'Locating Yourself',
   'Spiritual growth is not automatic.',
   'What is your current spiritual state? Write a short reflection.',
   'Ask God to reveal areas needing growth.',
   false, null, '[]'::jsonb),
  (2, 1, 'Chapter 2', 'Characteristics of Spiritual Babies',
   'Spiritual babies are emotionally driven and easily offended.',
   'Record 3 situations where emotions controlled your actions.',
   'Pray for emotional maturity.',
   false, null, '[]'::jsonb),
  (3, 1, 'Chapter 2', 'Identifying Babyhood Patterns',
   'Immaturity reveals itself through self-centeredness and instability.',
   'Identify one immature behavior and develop a corrective action step.',
   'Ask God for discipline and stability.',
   false, null, '[]'::jsonb),
  (4, 1, 'Chapter 3', 'Spiritual Childhood',
   'Spiritual children begin developing responsibility and consistency.',
   'Evaluate your current spiritual disciplines.',
   'Pray for consistency.',
   false, null, '[]'::jsonb),
  (5, 1, 'Chapter 3', 'Developing Responsibility',
   'Growth requires personal ownership.',
   'Take ownership of one neglected spiritual discipline.',
   'Ask God for diligence.',
   false, null, '[]'::jsonb),
  (6, 1, 'Chapter 4', 'Spiritual Manhood',
   'Mature believers live by God''s Word and influence others.',
   'List 5 qualities of mature believers you admire.',
   'Pray for maturity and influence.',
   false, null, '[]'::jsonb),
  (7, 1, 'Review', 'Weekly Assessment',
   'Honest evaluation produces growth.',
   'Reflect on this week and determine your current spiritual stage.',
   'Dedicate one growth area to God.',
   true,
   'Identify one major area of spiritual immaturity and intentionally work on it throughout the week.',
   '[]'::jsonb),

-- WEEK 2: WALKING WITH YOUR FATHER
  (8, 2, 'Chapter 5', 'Walking With Your Father',
   'Christianity is relationship before responsibility.',
   'Spend 20 minutes in uninterrupted fellowship with God. Reflect on the experience.',
   'Develop intimacy with God.',
   false, null, '[]'::jsonb),
  (9, 2, 'Chapter 5', 'Developing Fellowship',
   'Fellowship grows through consistency.',
   'Remove one distraction from your devotional life.',
   'Pray for deeper communion with God.',
   false, null, '[]'::jsonb),
  (10, 2, 'Chapter 6', 'Walking in Love',
   'Love is the evidence of spiritual maturity.',
   'Pray for and bless a difficult person.',
   'Ask God to increase your love walk.',
   false, null, '[]'::jsonb),
  (11, 2, 'Chapter 6', 'The Love Test',
   'Love is proven under pressure.',
   'Practice patience when criticized or offended. Reflect on it.',
   'Pray for grace in relationships.',
   false, null, '[]'::jsonb),
  (12, 2, 'Chapter 7', 'Receiving Knowledge',
   'Growth requires knowledge, understanding, and application.',
   'Study Ephesians chapter 4 and write down lessons learned.',
   'Pray for spiritual understanding.',
   false, null, '[]'::jsonb),
  (13, 2, 'Chapter 7', 'Applying Knowledge',
   'Truth transforms only when applied.',
   'Create one action step from a biblical truth learned recently.',
   'Pray for obedience.',
   false, null, '[]'::jsonb),
  (14, 2, 'Review', 'Weekly Assessment',
   'Relationship with God must continually deepen.',
   'Evaluate your growth in fellowship and love this week.',
   'Commit to a daily devotional routine.',
   true,
   'Spend at least 30 minutes daily in prayer, worship, and Bible study.',
   '[]'::jsonb),

-- WEEK 3: THE SPIRITUAL MAN
  (15, 3, 'Chapter 8', 'What Manner of Man Are You?',
   'There are natural, carnal, and spiritual people.',
   'Identify which category best describes your current life.',
   'Pray for spiritual growth.',
   false, null, '[]'::jsonb),
  (16, 3, 'Chapter 9', 'The Natural Man',
   'The natural man depends on human reasoning.',
   'Identify areas where you trust your senses more than God''s Word.',
   'Pray for renewed faith.',
   false, null, '[]'::jsonb),
  (17, 3, 'Chapter 10', 'The Carnal Man',
   'Carnality limits spiritual growth.',
   'Assess areas of jealousy, pride, strife, or unforgiveness.',
   'Pray for deliverance from fleshly habits.',
   false, null, '[]'::jsonb),
  (18, 3, 'Chapter 10', 'Identifying Carnal Patterns',
   'What is tolerated becomes strengthened.',
   'Replace three fleshly habits with spiritual disciplines. List them.',
   'Pray for transformation.',
   false, null, '[]'::jsonb),
  (19, 3, 'Chapter 11', 'The Spiritual Man',
   'Spiritual believers are led by the Holy Spirit.',
   'Evaluate yourself using the Fruit of the Spirit (Galatians 5:22-23).',
   'Pray for greater sensitivity to the Holy Spirit.',
   false, null, '[]'::jsonb),
  (20, 3, 'Chapter 12', 'The Right Diet',
   'Spiritual growth depends on spiritual nourishment.',
   'Track your spiritual diet (what you watched, listened to, read) for one day.',
   'Pray for hunger for God''s Word.',
   false, null, '[]'::jsonb),
  (21, 3, 'Chapter 13', 'A Word of Encouragement',
   'Spiritual growth is lifelong and progressive.',
   'Complete a personal growth reflection.',
   'Thank God for growth and future development.',
   true,
   'Build a sustainable spiritual growth routine that includes: Daily Prayer + PT, Bible Reading, Fellowship, fasting, and obedience through submission and accountability.',
   '[]'::jsonb)
on conflict (day_number) do update set
  week_number = excluded.week_number,
  chapter = excluded.chapter,
  topic = excluded.topic,
  key_truth = excluded.key_truth,
  practical_exercise = excluded.practical_exercise,
  prayer_focus = excluded.prayer_focus,
  is_review_day = excluded.is_review_day,
  weekly_challenge = excluded.weekly_challenge;
